language: python
matrix:
    include:
        - os: linux
          python: 3.5
          dist: xenial
        - os: linux
          python: 3.6
          dist: xenial
        - os: linux
          python: 3.7
          dist: xenial
        - os: linux
          python: 3.8-dev
          dist: xenial
        # shamelessly stolen from https://github.com/pyload/pyload
        - os: osx
          language: sh
          env:
            - HOMEBREW_NO_INSTALL_CLEANUP=1
            - HOMEBREW_NO_ANALYTICS=1
          before_cache:
            - rm -f "$HOME/Library/Caches/pip/log/debug.log"
          cache:
            directories:
              - "$HOME/Library/Caches/pip"
          addons:
            homebrew:
              packages: python3
          before_install:
            - python3 -m pip install --upgrade virtualenv
            - virtualenv -p python3 --system-site-packages "$HOME/venv"
            - source "$HOME/venv/bin/activate"
install:
    - pip install .[tests]
    - pip install coveralls
script: pytest
after_success:
  - coveralls
